// Mock data for products
export const mockProducts = [
  {
    id: '1',
    name: 'Paracetamol 500mg',
    price: 15000,
    category: 'Analgesik',
    image: '/placeholder.png',
    stock: 100,
    description: 'Obat pereda nyeri dan penurun demam',
    location: 'Rak A-1',
    unit: 'Strip',
    expiry: '2025-12-31',
    product_code: 'MED001',
    product_name: 'Paracetamol 500mg',
    price_input: 15000,
    qty: 100,
    sales_unit: 'Strip'
  },
  {
    id: '2',
    name: 'Amoxicillin 500mg',
    price: 25000,
    category: 'Antibiotik',
    image: '/placeholder.png',
    stock: 75,
    description: 'Antibiotik untuk infeksi bakteri',
    location: 'Rak B-2',
    unit: 'Strip',
    expiry: '2025-10-15',
    product_code: 'MED002',
    product_name: 'Amoxicillin 500mg',
    price_input: 25000,
    qty: 75,
    sales_unit: 'Strip'
  },
  {
    id: '3',
    name: 'Vitamin C 1000mg',
    price: 35000,
    category: 'Vitamin',
    image: '/placeholder.png',
    stock: 50,
    description: 'Suplemen untuk meningkatkan daya tahan tubuh',
    location: 'Rak C-3',
    unit: 'Botol',
    expiry: '2026-05-20',
    product_code: 'MED003',
    product_name: 'Vitamin C 1000mg',
    price_input: 35000,
    qty: 50,
    sales_unit: 'Botol'
  },
  {
    id: '4',
    name: 'Antasida',
    price: 18000,
    category: 'Pencernaan',
    image: '/placeholder.png',
    stock: 60,
    description: 'Meredakan sakit maag dan keasaman lambung',
    location: 'Rak D-1',
    unit: 'Botol',
    expiry: '2025-08-10',
    product_code: 'MED004',
    product_name: 'Antasida',
    price_input: 18000,
    qty: 60,
    sales_unit: 'Botol'
  },
  {
    id: '5',
    name: 'Ibuprofen 400mg',
    price: 22000,
    category: 'Analgesik',
    image: '/placeholder.png',
    stock: 45,
    description: 'Anti inflamasi non steroid untuk nyeri dan peradangan',
    location: 'Rak A-2',
    unit: 'Strip',
    expiry: '2025-11-05',
    product_code: 'MED005',
    product_name: 'Ibuprofen 400mg',
    price_input: 22000,
    qty: 45,
    sales_unit: 'Strip'
  },
  {
    id: '6',
    name: 'Cetirizine 10mg',
    price: 12000,
    category: 'Antihistamin',
    image: '/placeholder.png',
    stock: 80,
    description: 'Antihistamin untuk alergi dan gatal-gatal',
    location: 'Rak E-1',
    unit: 'Strip',
    expiry: '2026-01-15',
    product_code: 'MED006',
    product_name: 'Cetirizine 10mg',
    price_input: 12000,
    qty: 80,
    sales_unit: 'Strip'
  },
  {
    id: '7',
    name: 'Masker Medis (50pcs)',
    price: 50000,
    category: 'Alat Kesehatan',
    image: '/placeholder.png',
    stock: 30,
    description: 'Masker sekali pakai untuk perlindungan kesehatan',
    location: 'Rak F-1',
    unit: 'Box',
    expiry: '2027-01-01',
    product_code: 'MED007',
    product_name: 'Masker Medis (50pcs)',
    price_input: 50000,
    qty: 30,
    sales_unit: 'Box'
  },
  {
    id: '8',
    name: 'Betadine 60ml',
    price: 28000,
    category: 'Antiseptik',
    image: '/placeholder.png',
    stock: 40,
    description: 'Antiseptik untuk membersihkan luka',
    location: 'Rak F-2',
    unit: 'Botol',
    expiry: '2026-05-10',
    product_code: 'MED008',
    product_name: 'Betadine 60ml',
    price_input: 28000,
    qty: 40,
    sales_unit: 'Botol'
  },
  {
    id: '9',
    name: 'Plester Luka (20pcs)',
    price: 15000,
    category: 'Alat Kesehatan',
    image: '/placeholder.png',
    stock: 50,
    description: 'Plester untuk menutup luka kecil',
    location: 'Rak F-3',
    unit: 'Box',
    expiry: '2027-03-15',
    product_code: 'MED009',
    product_name: 'Plester Luka (20pcs)',
    price_input: 15000,
    qty: 50,
    sales_unit: 'Box'
  },
  {
    id: '10',
    name: 'Minyak Kayu Putih 60ml',
    price: 32000,
    category: 'Herbal',
    image: '/placeholder.png',
    stock: 35,
    description: 'Minyak esensial untuk meredakan gejala flu dan nyeri otot',
    location: 'Rak G-1',
    unit: 'Botol',
    expiry: '2026-08-20',
    product_code: 'MED010',
    product_name: 'Minyak Kayu Putih 60ml',
    price_input: 32000,
    qty: 35,
    sales_unit: 'Botol'
  },
  {
    id: '11',
    name: 'Thermometer Digital',
    price: 85000,
    category: 'Alat Kesehatan',
    image: '/placeholder.png',
    stock: 20,
    description: 'Alat pengukur suhu tubuh digital dengan akurasi tinggi',
    location: 'Rak G-2',
    unit: 'Pcs',
    expiry: '2030-01-01',
    product_code: 'MED011',
    product_name: 'Thermometer Digital',
    price_input: 85000,
    qty: 20,
    sales_unit: 'Pcs'
  },
  {
    id: '12',
    name: 'Tensimeter Digital',
    price: 350000,
    category: 'Alat Kesehatan',
    image: '/placeholder.png',
    stock: 10,
    description: 'Alat pengukur tekanan darah otomatis',
    location: 'Rak G-3',
    unit: 'Pcs',
    expiry: '2030-01-01',
    product_code: 'MED012',
    product_name: 'Tensimeter Digital',
    price_input: 350000,
    qty: 10,
    sales_unit: 'Pcs'
  },
  {
    id: '13',
    name: 'Multivitamin Harian',
    price: 75000,
    category: 'Vitamin',
    image: '/placeholder.png',
    stock: 40,
    description: 'Suplemen multivitamin untuk menjaga kesehatan tubuh',
    location: 'Rak C-2',
    unit: 'Botol',
    expiry: '2026-04-15',
    product_code: 'MED013',
    product_name: 'Multivitamin Harian',
    price_input: 75000,
    qty: 40,
    sales_unit: 'Botol'
  },
  {
    id: '14',
    name: 'Madu Murni 250ml',
    price: 65000,
    category: 'Herbal',
    image: '/placeholder.png',
    stock: 25,
    description: 'Madu alami untuk meningkatkan daya tahan tubuh',
    location: 'Rak G-4',
    unit: 'Botol',
    expiry: '2026-10-10',
    product_code: 'MED014',
    product_name: 'Madu Murni 250ml',
    price_input: 65000,
    qty: 25,
    sales_unit: 'Botol'
  },
  {
    id: '15',
    name: 'Hand Sanitizer 100ml',
    price: 25000,
    category: 'Antiseptik',
    image: '/placeholder.png',
    stock: 60,
    description: 'Pembersih tangan antiseptik untuk membunuh kuman',
    location: 'Rak F-4',
    unit: 'Botol',
    expiry: '2026-06-30',
    product_code: 'MED015',
    product_name: 'Hand Sanitizer 100ml',
    price_input: 25000,
    qty: 60,
    sales_unit: 'Botol'
  },
  {
    id: '16',
    name: 'Captopril 25mg',
    price: 18500,
    category: 'Kardiovaskular',
    image: '/placeholder.png',
    stock: 60,
    description: 'Obat untuk tekanan darah tinggi',
    location: 'Rak H-3',
    unit: 'Strip',
    expiry: '2025-11-30',
    product_code: 'MED016',
    product_name: 'Captopril 25mg',
    price_input: 18500,
    qty: 60,
    sales_unit: 'Strip'
  },
  {
    id: '17',
    name: 'Diazepam 5mg',
    price: 42000,
    category: 'Psikotropika',
    image: '/placeholder.png',
    stock: 25,
    description: 'Obat penenang dan anti kejang',
    location: 'Rak K-1',
    unit: 'Strip',
    expiry: '2025-08-25',
    product_code: 'MED017',
    product_name: 'Diazepam 5mg',
    price_input: 42000,
    qty: 25,
    sales_unit: 'Strip'
  },
  {
    id: '18',
    name: 'Cefixime 100mg',
    price: 65000,
    category: 'Antibiotik',
    image: '/placeholder.png',
    stock: 40,
    description: 'Antibiotik spektrum luas untuk infeksi bakteri',
    location: 'Rak B-3',
    unit: 'Strip',
    expiry: '2026-02-10',
    product_code: 'MED018',
    product_name: 'Cefixime 100mg',
    price_input: 65000,
    qty: 40,
    sales_unit: 'Strip'
  },
  {
    id: '19',
    name: 'Lansoprazole 30mg',
    price: 38000,
    category: 'Pencernaan',
    image: '/placeholder.png',
    stock: 55,
    description: 'Obat untuk mengurangi produksi asam lambung',
    location: 'Rak D-4',
    unit: 'Strip',
    expiry: '2025-10-05',
    product_code: 'MED019',
    product_name: 'Lansoprazole 30mg',
    price_input: 38000,
    qty: 55,
    sales_unit: 'Strip'
  },
  {
    id: '20',
    name: 'Minyak Kayu Putih 60ml',
    price: 25000,
    category: 'Herbal',
    image: '/placeholder.png',
    stock: 70,
    description: 'Minyak esensial untuk pereda nyeri dan pilek',
    location: 'Rak L-1',
    unit: 'Botol',
    expiry: '2026-06-15',
    product_code: 'MED020',
    product_name: 'Minyak Kayu Putih 60ml',
    price_input: 25000,
    qty: 70,
    sales_unit: 'Botol'
  },
  {
    id: '21',
    name: 'Vitamin B Complex',
    price: 28000,
    category: 'Vitamin',
    image: '/placeholder.png',
    stock: 65,
    description: 'Suplemen vitamin B kompleks untuk kesehatan saraf dan metabolisme',
    location: 'Rak C-4',
    unit: 'Botol',
    expiry: '2026-04-20',
    product_code: 'MED021',
    product_name: 'Vitamin B Complex',
    price_input: 28000,
    qty: 65,
    sales_unit: 'Botol'
  },
  {
    id: '22',
    name: 'Fluconazole 150mg',
    price: 55000,
    category: 'Antijamur',
    image: '/placeholder.png',
    stock: 30,
    description: 'Obat antijamur untuk infeksi jamur sistemik',
    location: 'Rak M-1',
    unit: 'Strip',
    expiry: '2025-12-15',
    product_code: 'MED022',
    product_name: 'Fluconazole 150mg',
    price_input: 55000,
    qty: 30,
    sales_unit: 'Strip'
  },
  {
    id: '23',
    name: 'Acarbose 50mg',
    price: 48000,
    category: 'Antidiabetik',
    image: '/placeholder.png',
    stock: 45,
    description: 'Obat untuk mengontrol gula darah setelah makan',
    location: 'Rak G-2',
    unit: 'Strip',
    expiry: '2026-01-25',
    product_code: 'MED023',
    product_name: 'Acarbose 50mg',
    price_input: 48000,
    qty: 45,
    sales_unit: 'Strip'
  },
  {
    id: '24',
    name: 'Calcium Lactate 500mg',
    price: 32000,
    category: 'Mineral',
    image: '/placeholder.png',
    stock: 60,
    description: 'Suplemen kalsium untuk kesehatan tulang',
    location: 'Rak N-1',
    unit: 'Botol',
    expiry: '2026-03-10',
    product_code: 'MED024',
    product_name: 'Calcium Lactate 500mg',
    price_input: 32000,
    qty: 60,
    sales_unit: 'Botol'
  },
  {
    id: '25',
    name: 'Ciprofloxacin 500mg',
    price: 45000,
    category: 'Antibiotik',
    image: '/placeholder.png',
    stock: 50,
    description: 'Antibiotik fluoroquinolon untuk infeksi bakteri',
    location: 'Rak B-4',
    unit: 'Strip',
    expiry: '2025-09-20',
    product_code: 'MED025',
    product_name: 'Ciprofloxacin 500mg',
    price_input: 45000,
    qty: 50,
    sales_unit: 'Strip'
  },
  {
    id: '26',
    name: 'Mefenamic Acid 500mg',
    price: 15000,
    category: 'Analgesik',
    image: '/placeholder.png',
    stock: 75,
    description: 'Obat pereda nyeri dan anti inflamasi',
    location: 'Rak A-3',
    unit: 'Strip',
    expiry: '2025-11-15',
    product_code: 'MED026',
    product_name: 'Mefenamic Acid 500mg',
    price_input: 15000,
    qty: 75,
    sales_unit: 'Strip'
  },
  {
    id: '27',
    name: 'Loperamide 2mg',
    price: 12500,
    category: 'Pencernaan',
    image: '/placeholder.png',
    stock: 80,
    description: 'Obat untuk diare',
    location: 'Rak D-5',
    unit: 'Strip',
    expiry: '2026-02-25',
    product_code: 'MED027',
    product_name: 'Loperamide 2mg',
    price_input: 12500,
    qty: 80,
    sales_unit: 'Strip'
  },
  {
    id: '28',
    name: 'Allopurinol 300mg',
    price: 22000,
    category: 'Asam Urat',
    image: '/placeholder.png',
    stock: 55,
    description: 'Obat untuk menurunkan kadar asam urat',
    location: 'Rak O-1',
    unit: 'Strip',
    expiry: '2025-10-10',
    product_code: 'MED028',
    product_name: 'Allopurinol 300mg',
    price_input: 22000,
    qty: 55,
    sales_unit: 'Strip'
  },
  {
    id: '29',
    name: 'Furosemide 40mg',
    price: 18000,
    category: 'Diuretik',
    image: '/placeholder.png',
    stock: 60,
    description: 'Obat diuretik untuk mengatasi retensi cairan',
    location: 'Rak P-1',
    unit: 'Strip',
    expiry: '2025-12-05',
    product_code: 'MED029',
    product_name: 'Furosemide 40mg',
    price_input: 18000,
    qty: 60,
    sales_unit: 'Strip'
  },
  {
    id: '30',
    name: 'Dextromethorpan Sirup 60ml',
    price: 28000,
    category: 'Batuk',
    image: '/placeholder.png',
    stock: 40,
    description: 'Obat batuk kering',
    location: 'Rak Q-1',
    unit: 'Botol',
    expiry: '2026-01-30',
    product_code: 'MED030',
    product_name: 'Dextromethorpan Sirup 60ml',
    price_input: 28000,
    qty: 40,
    sales_unit: 'Botol'
  }
];

// Mock data for transactions
export const mockTransactions = {
  today: {
    total: 1250000,
    count: 15,
    types: {
      tunai: 10,
      kartu: 3,
      ewallet: 2
    }
  },
  yesterday: {
    total: 980000,
    count: 12,
    types: {
      tunai: 8,
      kartu: 2,
      ewallet: 2
    }
  }
};

// Mock data for buyers
export const mockBuyers = {
  today: 12,
  yesterday: 10
};
